description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 9
    - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
      with:
        cache: pnpm
        node-version: "20"
    - run: pnpm install --frozen-lockfile
      shell: bash
  using: composite
