description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 9
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
      with:
        cache: pnpm
        node-version: "22"
    - run: pnpm install --frozen-lockfile
      shell: bash
  using: composite
